import { Section } from '@/types';

export const sections: Section[] = [
  {
    id: 'basic',
    name: '基本情報',
    description: '基本的なプロフィール情報を入力してください',
    questions: [
      { id: 'name', text: '氏名', type: 'text', required: true },
      { id: 'department', text: '所属部署 / チーム名', type: 'text' },
      { id: 'role', text: '現在の役割 / 職種', type: 'text' },
      { id: 'years', text: '勤続年数', type: 'text' },
      {
        id: 'age',
        text: '年代',
        type: 'select',
        options: [
          { value: '10s', label: '10代' },
          { value: '20s', label: '20代' },
          { value: '30s', label: '30代' },
          { value: '40s', label: '40代' },
          { value: '50s', label: '50代以上' },
        ],
      },
      {
        id: 'theme',
        text: 'このプログラムで特に知りたいテーマがあれば教えてください',
        type: 'text',
        placeholder: '例：自分の強みの活かし方、対人関係の改善など',
      },
    ],
  },
  {
    id: 'current_self',
    name: '現在の自分の特徴',
    description: '今の自分自身について振り返ってみてください',
    questions: [
      {
        id: 'strengths',
        text: '自分の強みだと思うものを5つ挙げてください',
        type: 'text',
        placeholder: '例：論理的思考、共感力、粘り強さ...',
      },
      {
        id: 'praised_points',
        text: '周囲からよく言われる長所を3つ挙げてください',
        type: 'text',
      },
      {
        id: 'weaknesses',
        text: '自分で感じる苦手・弱みを3つ挙げてください',
        type: 'text',
      },
      {
        id: 'misunderstood',
        text: '周囲から誤解されやすいと感じる点はありますか',
        type: 'text',
      },
      {
        id: 'best_working',
        text: 'どんな時に最も自分らしく働けますか',
        type: 'text',
      },
      {
        id: 'hardest_time',
        text: 'どんな時に最も苦しくなりますか',
        type: 'text',
      },
      {
        id: 'stress_reactions',
        text: 'ストレスがかかった時に出やすい反応を教えてください',
        type: 'multiSelect',
        options: [
          { value: 'silent', label: '無口になる' },
          { value: 'irritable', label: 'イライラしやすくなる' },
          { value: 'overthink', label: '考えすぎる' },
          { value: 'cannot_ask', label: '人に頼れなくなる' },
          { value: 'overwork', label: '過剰に頑張る' },
          { value: 'nothing', label: '何もしたくなくなる' },
          { value: 'avoid', label: '人を避ける' },
          { value: 'emotional', label: '感情的になる' },
          { value: 'insomnia', label: '眠れなくなる' },
          { value: 'other', label: 'その他' },
        ],
      },
      {
        id: 'asking_help',
        text: '人に頼ることについて最も近いものを選んでください',
        type: 'select',
        options: [
          { value: 'good', label: '得意' },
          { value: 'ok', label: 'ある程度できる' },
          { value: 'bit_hard', label: '少し苦手' },
          { value: 'hard', label: 'かなり苦手' },
        ],
      },
      {
        id: 'when_denied',
        text: '誰かに否定された時、どんな反応が出やすいですか',
        type: 'text',
      },
      {
        id: 'inner_voice',
        text: 'うまくいっていない時、自分の中でよく出る言葉は何ですか',
        type: 'text',
        placeholder: '例：「もっと頑張らないと」「自分が悪い」「どうせ無理」など',
      },
    ],
  },
  {
    id: 'diagnosis',
    name: '診断結果',
    description: '各種診断結果をアップロード・入力してください',
    questions: [
      {
        id: 'clifton_file',
        text: 'CliftonStrengths 34結果ファイルをアップロードしてください',
        type: 'file',
        hint: 'PDF、画像、またはテキストファイル',
      },
      {
        id: 'mbti_file',
        text: 'MBTI結果ファイルまたはスクリーンショットをアップロードしてください',
        type: 'file',
      },
      {
        id: 'other_file',
        text: 'その他の診断結果があればアップロードしてください',
        type: 'file',
      },
      {
        id: 'clifton_fit',
        text: 'CliftonStrengthsを見て、特にしっくりきた資質は何ですか',
        type: 'text',
      },
      {
        id: 'clifton_discomfort',
        text: 'CliftonStrengthsを見て、違和感があった資質は何ですか',
        type: 'text',
      },
      {
        id: 'bottom_fit',
        text: '下位資質を見て、「確かに自分っぽくない」と思ったものはありますか',
        type: 'text',
      },
      {
        id: 'bottom_unused',
        text: '下位資質を見て、「苦手というより使ってこなかっただけかも」と思うものはありますか',
        type: 'text',
      },
      {
        id: 'mbti_fit',
        text: 'MBTIを見て、合っている点・違和感のある点を書いてください',
        type: 'text',
      },
    ],
  },
  {
    id: 'family',
    name: '家族構成と家庭の空気',
    description: '育った環境について振り返ってください',
    questions: [
      {
        id: 'siblings',
        text: '兄弟姉妹構成を教えてください',
        type: 'text',
        placeholder: '例：兄1人、妹1人',
      },
      {
        id: 'birth_order',
        text: '自分は何番目でしたか',
        type: 'select',
        options: [
          { value: 'first', label: '長子' },
          { value: 'middle', label: '真ん中' },
          { value: 'youngest', label: '末っ子' },
          { value: 'only', label: '一人っ子' },
          { value: 'other', label: 'その他' },
        ],
      },
      {
        id: 'home_atmosphere',
        text: '家庭の空気を一言で表すと何でしたか',
        type: 'text',
        placeholder: '例：穏やか、緊張感がある、にぎやか...',
      },
      {
        id: 'home_safety',
        text: '家庭に安心感はありましたか',
        type: 'select',
        options: [
          { value: 'very', label: 'とてもあった' },
          { value: 'somewhat', label: 'ある程度あった' },
          { value: 'little', label: 'あまりなかった' },
          { value: 'none', label: 'ほとんどなかった' },
        ],
      },
      {
        id: 'home_tension',
        text: '家庭に緊張感はありましたか',
        type: 'select',
        options: [
          { value: 'very', label: 'とてもあった' },
          { value: 'somewhat', label: 'ある程度あった' },
          { value: 'little', label: 'あまりなかった' },
          { value: 'none', label: 'ほとんどなかった' },
        ],
      },
      { id: 'father', text: '父はどんな人でしたか', type: 'text' },
      { id: 'mother', text: '母はどんな人でしたか', type: 'text' },
      { id: 'parents_relationship', text: '親同士の関係はどう見えていましたか', type: 'text' },
      { id: 'influential_person', text: '家の中で一番影響力が強かった人は誰でしたか', type: 'text' },
      {
        id: 'position_at_home',
        text: '子どもの頃、家の中で自分はどんな立ち位置だったと思いますか',
        type: 'text',
      },
    ],
  },
  {
    id: 'childhood_role',
    name: '子どもの頃の役割',
    description: '幼少期の自分について振り返ってください',
    questions: [
      {
        id: 'childhood_self',
        text: '子どもの頃の自分を一言で表すとどんな子でしたか',
        type: 'text',
      },
      {
        id: 'home_role',
        text: '家で自分が担っていた役割があれば教えてください',
        type: 'multiSelect',
        options: [
          { value: 'responsible', label: 'しっかり者' },
          { value: 'mediator', label: '調整役' },
          { value: 'mood_maker', label: 'ムードメーカー' },
          { value: 'patient', label: '我慢する子' },
          { value: 'trouble', label: '問題児' },
          { value: 'expected', label: '期待される子' },
          { value: 'invisible', label: '目立たない子' },
          { value: 'spoiled', label: '甘える子' },
          { value: 'parent_support', label: '親を支える子' },
          { value: 'caretaker', label: '下の子の面倒を見る子' },
          { value: 'other', label: 'その他' },
        ],
      },
      { id: 'praised_for', text: '何をすると褒められましたか', type: 'text' },
      { id: 'scolded_for', text: '何をすると怒られましたか', type: 'text' },
      { id: 'bad_atmosphere', text: '何をすると空気が悪くなりましたか', type: 'text' },
      {
        id: 'good_child',
        text: '自分が「いい子」でいるために意識していたことがあれば教えてください',
        type: 'text',
      },
      {
        id: 'show_weakness',
        text: '家で弱さを見せることはできましたか',
        type: 'select',
        options: [
          { value: 'very', label: 'かなりできた' },
          { value: 'somewhat', label: 'ある程度できた' },
          { value: 'little', label: 'あまりできなかった' },
          { value: 'none', label: 'ほとんどできなかった' },
        ],
      },
      {
        id: 'be_spoiled',
        text: '家で甘えることはできましたか',
        type: 'select',
        options: [
          { value: 'very', label: 'かなりできた' },
          { value: 'somewhat', label: 'ある程度できた' },
          { value: 'little', label: 'あまりできなかった' },
          { value: 'none', label: 'ほとんどできなかった' },
        ],
      },
      { id: 'support_person', text: '困った時に頼れた人はいましたか', type: 'text' },
      {
        id: 'had_to_try',
        text: '子どもの頃、「自分が頑張らないと」と感じる場面はありましたか',
        type: 'text',
      },
    ],
  },
  {
    id: 'love_safety',
    name: '愛され方・守り方',
    description: '承認や安全を得るための行動パターンについて',
    questions: [
      {
        id: 'loved_when',
        text: '子どもの頃、自分は何をすると愛される / 認められると感じていましたか',
        type: 'text',
      },
      {
        id: 'abandoned_when',
        text: '子どもの頃、自分は何をすると嫌われる / 見捨てられる気がしていましたか',
        type: 'text',
      },
      {
        id: 'safety_behavior',
        text: '家の中で安心するためにしていたことはありますか',
        type: 'text',
      },
      {
        id: 'defense_reaction',
        text: '自分を守るために身につけた反応があるとしたら何ですか',
        type: 'text',
      },
      {
        id: 'safety_belief',
        text: '次のうち、自分に最も近いものを選んでください',
        type: 'select',
        options: [
          { value: 'proper', label: 'ちゃんとしていれば大丈夫' },
          { value: 'results', label: '成果を出せば大丈夫' },
          { value: 'read_air', label: '空気を読めば大丈夫' },
          { value: 'cheerful', label: '明るくしていれば大丈夫' },
          { value: 'alone', label: '一人でやれば大丈夫' },
          { value: 'strong', label: '強くあれば大丈夫' },
          { value: 'useful', label: '役に立てば大丈夫' },
          { value: 'invisible', label: '目立たなければ大丈夫' },
          { value: 'other', label: 'その他' },
        ],
      },
      {
        id: 'reaction_useful',
        text: 'その反応は今も役立っていますか',
        type: 'select',
        options: [
          { value: 'very', label: 'とても役立っている' },
          { value: 'somewhat', label: '一部役立っている' },
          { value: 'painful', label: '今は苦しさの方が大きい' },
          { value: 'unknown', label: '分からない' },
        ],
      },
      {
        id: 'painful_reaction',
        text: '今の自分を苦しめている昔からの反応があれば教えてください',
        type: 'text',
      },
    ],
  },
  {
    id: 'loss',
    name: '大きな出来事と喪失体験',
    description: '人生の転機や痛みを伴う経験について',
    questions: [
      {
        id: 'big_events',
        text: '人生の中で大きかった出来事を3つまで教えてください',
        type: 'text',
      },
      {
        id: 'loss_experience',
        text: '人生の中で大きかった喪失体験があれば教えてください',
        type: 'text',
      },
      {
        id: 'life_changing',
        text: '自分の生き方が変わったと感じる出来事はありますか',
        type: 'text',
      },
      {
        id: 'painful_memory',
        text: '今も思い出すと胸が苦しくなる経験はありますか',
        type: 'text',
        hint: '任意回答',
      },
      {
        id: 'hard_to_talk',
        text: '今も人に話しづらい経験はありますか',
        type: 'text',
        hint: '任意回答',
      },
      {
        id: 'stronger_reaction',
        text: 'その経験以降、自分の中で強くなった反応はありますか',
        type: 'text',
      },
      {
        id: 'fear_of_losing',
        text: 'その経験以降、自分が失うことを怖くなったものは何ですか',
        type: 'text',
      },
      {
        id: 'never_let_go',
        text: 'その経験以降、自分が絶対に手放したくないものは何ですか',
        type: 'text',
      },
    ],
  },
  {
    id: 'defense',
    name: '防衛反応と深いパターン',
    description: '深層の反応パターンについて（任意回答）',
    optional: true,
    questions: [
      {
        id: 'hurt_reaction',
        text: '強く傷ついた時、自分はどんな反応を取りやすいですか',
        type: 'multiSelect',
        options: [
          { value: 'silent', label: '黙る' },
          { value: 'distance', label: '距離を取る' },
          { value: 'angry', label: '怒る' },
          { value: 'overwork', label: '過剰に頑張る' },
          { value: 'laugh', label: '笑ってごまかす' },
          { value: 'comply', label: '相手に合わせる' },
          { value: 'logic', label: '論理で処理する' },
          { value: 'self_blame', label: '自分を責める' },
          { value: 'cut_off', label: '相手を切る' },
          { value: 'numb', label: '何も感じないようにする' },
          { value: 'other', label: 'その他' },
        ],
      },
      {
        id: 'overreact_to',
        text: '何をされると、必要以上に強く反応してしまいますか',
        type: 'text',
      },
      {
        id: 'old_feeling',
        text: 'どんな場面で「昔の感覚」に戻る感じがありますか',
        type: 'text',
      },
      {
        id: 'relationship_pattern',
        text: 'よく繰り返す人間関係パターンがあれば教えてください',
        type: 'text',
      },
      {
        id: 'repeated_role',
        text: '上司、親しい相手、恋人、仲間などに対して、繰り返し取りがちな役割はありますか',
        type: 'text',
      },
      {
        id: 'biggest_fear',
        text: '自分が最も怖れているものは何ですか',
        type: 'text',
        placeholder: '例：見捨てられること、役に立てないこと、負けること、弱さを見せること など',
      },
      {
        id: 'life_rule',
        text: '無意識に従っている人生ルールがあれば教えてください',
        type: 'text',
        placeholder: '例：「弱音を吐いてはいけない」「負けてはいけない」など',
      },
      {
        id: 'rule_protected',
        text: 'そのルールは、昔は自分を守ってくれましたか',
        type: 'select',
        options: [
          { value: 'yes', label: 'はい' },
          { value: 'no', label: 'いいえ' },
          { value: 'unknown', label: '分からない' },
        ],
      },
      {
        id: 'rule_painful',
        text: 'そのルールは、今の自分を苦しめていますか',
        type: 'select',
        options: [
          { value: 'yes', label: 'はい' },
          { value: 'no', label: 'いいえ' },
          { value: 'unknown', label: '分からない' },
        ],
      },
      {
        id: 'want_to_loosen',
        text: '本当はもう少し緩めたい反応があれば教えてください',
        type: 'text',
      },
    ],
  },
  {
    id: 'work',
    name: '仕事・組織での表れ方',
    description: '職場での行動パターンについて',
    questions: [
      {
        id: 'family_pattern_at_work',
        text: '家族の中での役割を、今の職場でも繰り返している感覚はありますか',
        type: 'text',
      },
      {
        id: 'take_responsibility',
        text: 'どんな時に「自分がやらなければ」と背負いやすいですか',
        type: 'text',
      },
      {
        id: 'delegate_anxiety',
        text: '人に任せる時、どんな不安が出ますか',
        type: 'text',
      },
      {
        id: 'clash_type',
        text: 'どんなタイプの上司・同僚とぶつかりやすいですか',
        type: 'text',
      },
      {
        id: 'compatible_type',
        text: 'どんなタイプの上司・同僚と相性が良いですか',
        type: 'text',
      },
      {
        id: 'work_role',
        text: '職場で自分が自然に取りがちな役割は何ですか',
        type: 'multiSelect',
        options: [
          { value: 'leader', label: 'リーダー' },
          { value: 'mediator', label: '調整役' },
          { value: 'executor', label: '実行役' },
          { value: 'ideator', label: 'アイデア役' },
          { value: 'supporter', label: 'サポート役' },
          { value: 'firefighter', label: '火消し役' },
          { value: 'healer', label: '癒やし役' },
          { value: 'systematizer', label: '仕組み化役' },
          { value: 'challenger', label: '問題提起役' },
          { value: 'other', label: 'その他' },
        ],
      },
      {
        id: 'work_strength',
        text: '仕事で最も評価されやすい強みは何だと思いますか',
        type: 'text',
      },
      {
        id: 'work_misunderstanding',
        text: '仕事で最も誤解されやすい点は何だと思いますか',
        type: 'text',
      },
      {
        id: 'past_hindrance',
        text: '自分の過去由来の反応が、仕事の邪魔になる場面はありますか',
        type: 'text',
      },
      {
        id: 'ideal_environment',
        text: 'どんな環境なら、自分はもっと健全に強みを発揮できそうですか',
        type: 'text',
      },
    ],
  },
  {
    id: 'future',
    name: 'これから手放したいもの / 育てたいもの',
    description: '未来に向けて',
    questions: [
      {
        id: 'release_reaction',
        text: '今の自分が手放したい反応を教えてください',
        type: 'text',
      },
      {
        id: 'keep_strength',
        text: '今の自分が残したい強みを教えてください',
        type: 'text',
      },
      {
        id: 'new_way',
        text: '今後、自分が新しく身につけたい反応・在り方は何ですか',
        type: 'text',
      },
      {
        id: 'words_to_past',
        text: '今の自分が、過去の自分にかけるとしたらどんな言葉をかけますか',
        type: 'text',
      },
      {
        id: 'childhood_need',
        text: '子どもの頃の自分が一番欲しかったものは何だと思いますか',
        type: 'text',
      },
      {
        id: 'self_permission',
        text: '今の自分は、自分に何を許可してあげたいですか',
        type: 'text',
      },
      {
        id: 'future_theme',
        text: '今後の仕事や人生で、より大切にしたいテーマは何ですか',
        type: 'text',
      },
    ],
  },
];
